### PR TITLE
fix: Feedback addressed by @Marcony1 about adding to the badges as su…

### LINKED ISSUE #91: Add link to PyPI for the version badge
As mandated in the package review template, we need to show the current package aversion (on PyPI/conda)

Also pointed out by reviewers in external issue https://github.com/UBC-MDS/software-review-2024/issues/18.

### PR DESCRIPTION
**Pull request by Marcony1**
…ggested by @ella-irene

### CODE REVIEW

**Review by SoloSynth1 — APPROVED** [review]
LGTM!

**Comment by SoloSynth1** [comment]
@Marcony1, note that for the changes in documentation we should use the `docs:` prefix instead of `fix:`.

**Comment by SoloSynth1** [comment]
Merging to `main`.

**Comment by Marcony1** [comment]
Merging, thanks @SoloSynth1

**Comment by shawnhu444** [comment]
agreed on the changes

**Pull request merged**
