### PR TITLE
build: setting up permissions to API Token

### LINKED ISSUE #69: Set up semantic release GH actions

### PR DESCRIPTION
**Pull request by Marcony1**
Added permissions to the API TOKEN. Please let me know what you think.

### CODE REVIEW

**Review by SoloSynth1 — APPROVED** [review]
LGTM

**Comment by shawnhu444** [comment]
agreed on changes

**Comment by Marcony1** [comment]
Thank you

**Comment by SoloSynth1** [comment]
merging to `main`.

**Pull request merged**
