### PR TITLE
fix: replace outdated github action

### LINKED ISSUE #107: Semantic Release not properly triggered to build package
The current `ci-cd.yaml` skipped package building and release for`v2.1.0`.

### PR DESCRIPTION
**Pull request by SoloSynth1**
Closes #107.

### CODE REVIEW

**Review by Marcony1 — APPROVED** [review]
Approved

**Review by atabak-alishiri — COMMENTED** [review]
Thank you @SoloSynth1 , How can I test this? because it is part of the ci-cd file, I have no idea on testing it

**Comment by SoloSynth1** [comment]
> Thank you @SoloSynth1 , How can I test this? because it is part of the ci-cd file, I have no idea on testing it

Well I just looked up in the docs... this merge is sort of a test on its own. I guess if we really want to test it, we should change the `ci-cd.yaml` so that the `cd` part got triggered for every push, not just for releases.

**Comment by SoloSynth1** [comment]
@atabak-alishiri Actually this might be a good idea, testing it on this branch now

**Comment by SoloSynth1** [comment]
Seems fine. I will merge this into `main` once reverting the testing change. Thanks @atabak-alishiri @Marcony1 !

**Pull request merged**
